// Generated by gencpp from file roboy_middleware_msgs/HandCommand.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_HANDCOMMAND_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_HANDCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct HandCommand_
{
  typedef HandCommand_<ContainerAllocator> Type;

  HandCommand_()
    : hand_id(0)
    , gesture(0)
    , finger_pos()
    , finger_speed()  {
    }
  HandCommand_(const ContainerAllocator& _alloc)
    : hand_id(0)
    , gesture(0)
    , finger_pos(_alloc)
    , finger_speed(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _hand_id_type;
  _hand_id_type hand_id;

   typedef uint8_t _gesture_type;
  _gesture_type gesture;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _finger_pos_type;
  _finger_pos_type finger_pos;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _finger_speed_type;
  _finger_speed_type finger_speed;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> const> ConstPtr;

}; // struct HandCommand_

typedef ::roboy_middleware_msgs::HandCommand_<std::allocator<void> > HandCommand;

typedef boost::shared_ptr< ::roboy_middleware_msgs::HandCommand > HandCommandPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::HandCommand const> HandCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_middleware_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_middleware_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67aa5bc29db86e2d5f7f09f60811f24e";
  }

  static const char* value(const ::roboy_middleware_msgs::HandCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67aa5bc29db86e2dULL;
  static const uint64_t static_value2 = 0x5f7f09f60811f24eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/HandCommand";
  }

  static const char* value(const ::roboy_middleware_msgs::HandCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 hand_id\n"
"uint8 gesture\n"
"uint16[] finger_pos\n"
"uint8[] finger_speed\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::HandCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hand_id);
      stream.next(m.gesture);
      stream.next(m.finger_pos);
      stream.next(m.finger_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::HandCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::HandCommand_<ContainerAllocator>& v)
  {
    s << indent << "hand_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hand_id);
    s << indent << "gesture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gesture);
    s << indent << "finger_pos[]" << std::endl;
    for (size_t i = 0; i < v.finger_pos.size(); ++i)
    {
      s << indent << "  finger_pos[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.finger_pos[i]);
    }
    s << indent << "finger_speed[]" << std::endl;
    for (size_t i = 0; i < v.finger_speed.size(); ++i)
    {
      s << indent << "  finger_speed[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.finger_speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_HANDCOMMAND_H
