// Generated by gencpp from file roboy_middleware_msgs/HandStatus.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_HANDSTATUS_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_HANDSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct HandStatus_
{
  typedef HandStatus_<ContainerAllocator> Type;

  HandStatus_()
    : hand_id(0)
    , finger_pos()
    , finger_current()
    , gyro_data()
    , imu_data()  {
    }
  HandStatus_(const ContainerAllocator& _alloc)
    : hand_id(0)
    , finger_pos(_alloc)
    , finger_current(_alloc)
    , gyro_data(_alloc)
    , imu_data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _hand_id_type;
  _hand_id_type hand_id;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _finger_pos_type;
  _finger_pos_type finger_pos;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _finger_current_type;
  _finger_current_type finger_current;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _gyro_data_type;
  _gyro_data_type gyro_data;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _imu_data_type;
  _imu_data_type imu_data;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> const> ConstPtr;

}; // struct HandStatus_

typedef ::roboy_middleware_msgs::HandStatus_<std::allocator<void> > HandStatus;

typedef boost::shared_ptr< ::roboy_middleware_msgs::HandStatus > HandStatusPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::HandStatus const> HandStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_middleware_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_middleware_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0e7307277d4dcab3439944624663fb0";
  }

  static const char* value(const ::roboy_middleware_msgs::HandStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0e7307277d4dcabULL;
  static const uint64_t static_value2 = 0x3439944624663fb0ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/HandStatus";
  }

  static const char* value(const ::roboy_middleware_msgs::HandStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 hand_id\n"
"uint16[] finger_pos\n"
"uint32[] finger_current\n"
"uint32[] gyro_data\n"
"uint32[] imu_data\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::HandStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hand_id);
      stream.next(m.finger_pos);
      stream.next(m.finger_current);
      stream.next(m.gyro_data);
      stream.next(m.imu_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HandStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::HandStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::HandStatus_<ContainerAllocator>& v)
  {
    s << indent << "hand_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hand_id);
    s << indent << "finger_pos[]" << std::endl;
    for (size_t i = 0; i < v.finger_pos.size(); ++i)
    {
      s << indent << "  finger_pos[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.finger_pos[i]);
    }
    s << indent << "finger_current[]" << std::endl;
    for (size_t i = 0; i < v.finger_current.size(); ++i)
    {
      s << indent << "  finger_current[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.finger_current[i]);
    }
    s << indent << "gyro_data[]" << std::endl;
    for (size_t i = 0; i < v.gyro_data.size(); ++i)
    {
      s << indent << "  gyro_data[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.gyro_data[i]);
    }
    s << indent << "imu_data[]" << std::endl;
    for (size_t i = 0; i < v.imu_data.size(); ++i)
    {
      s << indent << "  imu_data[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.imu_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_HANDSTATUS_H
