// Generated by gencpp from file roboy_middleware_msgs/MotorConfigServiceRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCONFIGSERVICEREQUEST_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCONFIGSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roboy_middleware_msgs/MotorConfig.h>

namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct MotorConfigServiceRequest_
{
  typedef MotorConfigServiceRequest_<ContainerAllocator> Type;

  MotorConfigServiceRequest_()
    : legacy(false)
    , config()  {
    }
  MotorConfigServiceRequest_(const ContainerAllocator& _alloc)
    : legacy(false)
    , config(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _legacy_type;
  _legacy_type legacy;

   typedef  ::roboy_middleware_msgs::MotorConfig_<ContainerAllocator>  _config_type;
  _config_type config;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MotorConfigServiceRequest_

typedef ::roboy_middleware_msgs::MotorConfigServiceRequest_<std::allocator<void> > MotorConfigServiceRequest;

typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorConfigServiceRequest > MotorConfigServiceRequestPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorConfigServiceRequest const> MotorConfigServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_middleware_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_middleware_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02855ca08dfa32d21a88932308604231";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02855ca08dfa32d2ULL;
  static const uint64_t static_value2 = 0x1a88932308604231ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/MotorConfigServiceRequest";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool legacy\n"
"MotorConfig config\n"
"\n"
"================================================================================\n"
"MSG: roboy_middleware_msgs/MotorConfig\n"
"int32[] update_frequency\n"
"uint8[] motor\n"
"uint8[] control_mode\n"
"int32[] PWMLimit\n"
"int32[] IntegralLimit\n"
"int32[] Kp\n"
"int32[] Ki\n"
"int32[] Kd\n"
"int32[] deadband\n"
"int32[] setpoint\n"
"int32[] gearBoxRatio\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.legacy);
      stream.next(m.config);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorConfigServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::MotorConfigServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "legacy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.legacy);
    s << indent << "config: ";
    s << std::endl;
    Printer< ::roboy_middleware_msgs::MotorConfig_<ContainerAllocator> >::stream(s, indent + "  ", v.config);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCONFIGSERVICEREQUEST_H
