// Generated by gencpp from file roboy_middleware_msgs/EmergencyStopResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_EMERGENCYSTOPRESPONSE_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_EMERGENCYSTOPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roboy_middleware_msgs/ControllerState.h>

namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct EmergencyStopResponse_
{
  typedef EmergencyStopResponse_<ContainerAllocator> Type;

  EmergencyStopResponse_()
    : states()  {
    }
  EmergencyStopResponse_(const ContainerAllocator& _alloc)
    : states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::roboy_middleware_msgs::ControllerState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roboy_middleware_msgs::ControllerState_<ContainerAllocator> >::other >  _states_type;
  _states_type states;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EmergencyStopResponse_

typedef ::roboy_middleware_msgs::EmergencyStopResponse_<std::allocator<void> > EmergencyStopResponse;

typedef boost::shared_ptr< ::roboy_middleware_msgs::EmergencyStopResponse > EmergencyStopResponsePtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::EmergencyStopResponse const> EmergencyStopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_middleware_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_middleware_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1860ce0365aa3b59242b46bb77db6c62";
  }

  static const char* value(const ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1860ce0365aa3b59ULL;
  static const uint64_t static_value2 = 0x242b46bb77db6c62ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/EmergencyStopResponse";
  }

  static const char* value(const ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ControllerState[] states\n"
"\n"
"\n"
"================================================================================\n"
"MSG: roboy_middleware_msgs/ControllerState\n"
"int32 id\n"
"int8 state\n"
"\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmergencyStopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::EmergencyStopResponse_<ContainerAllocator>& v)
  {
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roboy_middleware_msgs::ControllerState_<ContainerAllocator> >::stream(s, indent + "    ", v.states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_EMERGENCYSTOPRESPONSE_H
