// Generated by gencpp from file roboy_middleware_msgs/MotorInfo.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORINFO_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct MotorInfo_
{
  typedef MotorInfo_<ContainerAllocator> Type;

  MotorInfo_()
    : setpoint()
    , control_mode()
    , Kp()
    , Ki()
    , Kd()
    , deadband()
    , IntegralLimit()
    , PWMLimit()
    , pwm()
    , communication_quality()
    , error_code()
    , gearBoxRatio()  {
    }
  MotorInfo_(const ContainerAllocator& _alloc)
    : setpoint(_alloc)
    , control_mode(_alloc)
    , Kp(_alloc)
    , Ki(_alloc)
    , Kd(_alloc)
    , deadband(_alloc)
    , IntegralLimit(_alloc)
    , PWMLimit(_alloc)
    , pwm(_alloc)
    , communication_quality(_alloc)
    , error_code(_alloc)
    , gearBoxRatio(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _setpoint_type;
  _setpoint_type setpoint;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _control_mode_type;
  _control_mode_type control_mode;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _Kp_type;
  _Kp_type Kp;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _Ki_type;
  _Ki_type Ki;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _Kd_type;
  _Kd_type Kd;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _deadband_type;
  _deadband_type deadband;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _IntegralLimit_type;
  _IntegralLimit_type IntegralLimit;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _PWMLimit_type;
  _PWMLimit_type PWMLimit;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _pwm_type;
  _pwm_type pwm;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _communication_quality_type;
  _communication_quality_type communication_quality;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _error_code_type;
  _error_code_type error_code;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _gearBoxRatio_type;
  _gearBoxRatio_type gearBoxRatio;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MotorInfo_

typedef ::roboy_middleware_msgs::MotorInfo_<std::allocator<void> > MotorInfo;

typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorInfo > MotorInfoPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorInfo const> MotorInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_middleware_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_middleware_msgs/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efed6a40bd0150d07743fdfc5f7f955c";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefed6a40bd0150d0ULL;
  static const uint64_t static_value2 = 0x7743fdfc5f7f955cULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/MotorInfo";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] setpoint\n"
"uint8[] control_mode\n"
"int32[] Kp\n"
"int32[] Ki\n"
"int32[] Kd\n"
"int32[] deadband\n"
"int32[] IntegralLimit\n"
"int32[] PWMLimit\n"
"int32[] pwm\n"
"int32[] communication_quality\n"
"int32[] error_code\n"
"int32[] gearBoxRatio\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
      stream.next(m.control_mode);
      stream.next(m.Kp);
      stream.next(m.Ki);
      stream.next(m.Kd);
      stream.next(m.deadband);
      stream.next(m.IntegralLimit);
      stream.next(m.PWMLimit);
      stream.next(m.pwm);
      stream.next(m.communication_quality);
      stream.next(m.error_code);
      stream.next(m.gearBoxRatio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::MotorInfo_<ContainerAllocator>& v)
  {
    s << indent << "setpoint[]" << std::endl;
    for (size_t i = 0; i < v.setpoint.size(); ++i)
    {
      s << indent << "  setpoint[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.setpoint[i]);
    }
    s << indent << "control_mode[]" << std::endl;
    for (size_t i = 0; i < v.control_mode.size(); ++i)
    {
      s << indent << "  control_mode[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.control_mode[i]);
    }
    s << indent << "Kp[]" << std::endl;
    for (size_t i = 0; i < v.Kp.size(); ++i)
    {
      s << indent << "  Kp[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Kp[i]);
    }
    s << indent << "Ki[]" << std::endl;
    for (size_t i = 0; i < v.Ki.size(); ++i)
    {
      s << indent << "  Ki[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Ki[i]);
    }
    s << indent << "Kd[]" << std::endl;
    for (size_t i = 0; i < v.Kd.size(); ++i)
    {
      s << indent << "  Kd[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.Kd[i]);
    }
    s << indent << "deadband[]" << std::endl;
    for (size_t i = 0; i < v.deadband.size(); ++i)
    {
      s << indent << "  deadband[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.deadband[i]);
    }
    s << indent << "IntegralLimit[]" << std::endl;
    for (size_t i = 0; i < v.IntegralLimit.size(); ++i)
    {
      s << indent << "  IntegralLimit[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.IntegralLimit[i]);
    }
    s << indent << "PWMLimit[]" << std::endl;
    for (size_t i = 0; i < v.PWMLimit.size(); ++i)
    {
      s << indent << "  PWMLimit[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.PWMLimit[i]);
    }
    s << indent << "pwm[]" << std::endl;
    for (size_t i = 0; i < v.pwm.size(); ++i)
    {
      s << indent << "  pwm[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pwm[i]);
    }
    s << indent << "communication_quality[]" << std::endl;
    for (size_t i = 0; i < v.communication_quality.size(); ++i)
    {
      s << indent << "  communication_quality[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.communication_quality[i]);
    }
    s << indent << "error_code[]" << std::endl;
    for (size_t i = 0; i < v.error_code.size(); ++i)
    {
      s << indent << "  error_code[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.error_code[i]);
    }
    s << indent << "gearBoxRatio[]" << std::endl;
    for (size_t i = 0; i < v.gearBoxRatio.size(); ++i)
    {
      s << indent << "  gearBoxRatio[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.gearBoxRatio[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORINFO_H
