// Generated by gencpp from file roboy_cognition_msgs/AudioInfo.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_AUDIOINFO_H
#define ROBOY_COGNITION_MSGS_MESSAGE_AUDIOINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct AudioInfo_
{
  typedef AudioInfo_<ContainerAllocator> Type;

  AudioInfo_()
    : frequency()
    , average_power()  {
    }
  AudioInfo_(const ContainerAllocator& _alloc)
    : frequency(_alloc)
    , average_power(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _frequency_type;
  _frequency_type frequency;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _average_power_type;
  _average_power_type average_power;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> const> ConstPtr;

}; // struct AudioInfo_

typedef ::roboy_cognition_msgs::AudioInfo_<std::allocator<void> > AudioInfo;

typedef boost::shared_ptr< ::roboy_cognition_msgs::AudioInfo > AudioInfoPtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::AudioInfo const> AudioInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_cognition_msgs': ['/home/sausy/Projects/roboy_hand/catkin/src/roboy_communication/roboy_cognition_msgs/msg', '/home/sausy/Projects/roboy_hand/catkin/devel/share/roboy_cognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b06171fe54f2668f04382a9767d00dfe";
  }

  static const char* value(const ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb06171fe54f2668fULL;
  static const uint64_t static_value2 = 0x04382a9767d00dfeULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/AudioInfo";
  }

  static const char* value(const ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] frequency\n"
"float32[] average_power\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency);
      stream.next(m.average_power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::AudioInfo_<ContainerAllocator>& v)
  {
    s << indent << "frequency[]" << std::endl;
    for (size_t i = 0; i < v.frequency.size(); ++i)
    {
      s << indent << "  frequency[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.frequency[i]);
    }
    s << indent << "average_power[]" << std::endl;
    for (size_t i = 0; i < v.average_power.size(); ++i)
    {
      s << indent << "  average_power[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.average_power[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_AUDIOINFO_H
