// Generated by gencpp from file roboy_cognition_msgs/DetectIceCreamResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_DETECTICECREAMRESPONSE_H
#define ROBOY_COGNITION_MSGS_MESSAGE_DETECTICECREAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct DetectIceCreamResponse_
{
  typedef DetectIceCreamResponse_<ContainerAllocator> Type;

  DetectIceCreamResponse_()
    : start_scooping()
    , end_scooping()
    , error_message()  {
    }
  DetectIceCreamResponse_(const ContainerAllocator& _alloc)
    : start_scooping(_alloc)
    , end_scooping(_alloc)
    , error_message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_scooping_type;
  _start_scooping_type start_scooping;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _end_scooping_type;
  _end_scooping_type end_scooping;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectIceCreamResponse_

typedef ::roboy_cognition_msgs::DetectIceCreamResponse_<std::allocator<void> > DetectIceCreamResponse;

typedef boost::shared_ptr< ::roboy_cognition_msgs::DetectIceCreamResponse > DetectIceCreamResponsePtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::DetectIceCreamResponse const> DetectIceCreamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_cognition_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_cognition_msgs/msg', '/home/sausy/Projects/Hand_openBionic/catkin/devel/share/roboy_cognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16fd345363711f9e984e0964e8b97477";
  }

  static const char* value(const ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16fd345363711f9eULL;
  static const uint64_t static_value2 = 0x984e0964e8b97477ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/DetectIceCreamResponse";
  }

  static const char* value(const ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point start_scooping\n"
"geometry_msgs/Point end_scooping\n"
"string error_message\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_scooping);
      stream.next(m.end_scooping);
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectIceCreamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::DetectIceCreamResponse_<ContainerAllocator>& v)
  {
    s << indent << "start_scooping: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start_scooping);
    s << indent << "end_scooping: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.end_scooping);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_DETECTICECREAMRESPONSE_H
