// Generated by gencpp from file roboy_cognition_msgs/RecognizedFaces.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZEDFACES_H
#define ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZEDFACES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct RecognizedFaces_
{
  typedef RecognizedFaces_<ContainerAllocator> Type;

  RecognizedFaces_()
    : names()
    , confidence()  {
    }
  RecognizedFaces_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , confidence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizedFaces_

typedef ::roboy_cognition_msgs::RecognizedFaces_<std::allocator<void> > RecognizedFaces;

typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizedFaces > RecognizedFacesPtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizedFaces const> RecognizedFacesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_cognition_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_cognition_msgs/msg', '/home/sausy/Projects/Hand_openBionic/catkin/devel/share/roboy_cognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1c93df92c259a3092c20b630d063988";
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1c93df92c259a30ULL;
  static const uint64_t static_value2 = 0x92c20b630d063988ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/RecognizedFaces";
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n"
"float64[] confidence\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizedFaces_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::RecognizedFaces_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "confidence[]" << std::endl;
    for (size_t i = 0; i < v.confidence.size(); ++i)
    {
      s << indent << "  confidence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.confidence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZEDFACES_H
