// Generated by gencpp from file roboy_simulation_msgs/GymStepRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_SIMULATION_MSGS_MESSAGE_GYMSTEPREQUEST_H
#define ROBOY_SIMULATION_MSGS_MESSAGE_GYMSTEPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_simulation_msgs
{
template <class ContainerAllocator>
struct GymStepRequest_
{
  typedef GymStepRequest_<ContainerAllocator> Type;

  GymStepRequest_()
    : controller(0)
    , set_points()
    , step_size(0.0)  {
    }
  GymStepRequest_(const ContainerAllocator& _alloc)
    : controller(0)
    , set_points(_alloc)
    , step_size(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _controller_type;
  _controller_type controller;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _set_points_type;
  _set_points_type set_points;

   typedef double _step_size_type;
  _step_size_type step_size;





  typedef boost::shared_ptr< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GymStepRequest_

typedef ::roboy_simulation_msgs::GymStepRequest_<std::allocator<void> > GymStepRequest;

typedef boost::shared_ptr< ::roboy_simulation_msgs::GymStepRequest > GymStepRequestPtr;
typedef boost::shared_ptr< ::roboy_simulation_msgs::GymStepRequest const> GymStepRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_simulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_simulation_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_simulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fbc3d3b20aed420307823da2f5eab50";
  }

  static const char* value(const ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fbc3d3b20aed420ULL;
  static const uint64_t static_value2 = 0x307823da2f5eab50ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_simulation_msgs/GymStepRequest";
  }

  static const char* value(const ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 controller\n"
"float64[] set_points\n"
"float64 step_size\n"
;
  }

  static const char* value(const ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller);
      stream.next(m.set_points);
      stream.next(m.step_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GymStepRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_simulation_msgs::GymStepRequest_<ContainerAllocator>& v)
  {
    s << indent << "controller: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controller);
    s << indent << "set_points[]" << std::endl;
    for (size_t i = 0; i < v.set_points.size(); ++i)
    {
      s << indent << "  set_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.set_points[i]);
    }
    s << indent << "step_size: ";
    Printer<double>::stream(s, indent + "  ", v.step_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_SIMULATION_MSGS_MESSAGE_GYMSTEPREQUEST_H
