// Generated by gencpp from file roboy_control_msgs/ControlLeds.msg
// DO NOT EDIT!


#ifndef ROBOY_CONTROL_MSGS_MESSAGE_CONTROLLEDS_H
#define ROBOY_CONTROL_MSGS_MESSAGE_CONTROLLEDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_control_msgs
{
template <class ContainerAllocator>
struct ControlLeds_
{
  typedef ControlLeds_<ContainerAllocator> Type;

  ControlLeds_()
    : mode(0)
    , duration(0)  {
    }
  ControlLeds_(const ContainerAllocator& _alloc)
    : mode(0)
    , duration(0)  {
  (void)_alloc;
    }



   typedef int16_t _mode_type;
  _mode_type mode;

   typedef int32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> const> ConstPtr;

}; // struct ControlLeds_

typedef ::roboy_control_msgs::ControlLeds_<std::allocator<void> > ControlLeds;

typedef boost::shared_ptr< ::roboy_control_msgs::ControlLeds > ControlLedsPtr;
typedef boost::shared_ptr< ::roboy_control_msgs::ControlLeds const> ControlLedsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_control_msgs::ControlLeds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'roboy_control_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_control_msgs/msg', '/home/sausy/Projects/Hand_openBionic/catkin/devel/share/roboy_control_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbdf6d76365c7274e13bc5d8007f65ca";
  }

  static const char* value(const ::roboy_control_msgs::ControlLeds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbdf6d76365c7274ULL;
  static const uint64_t static_value2 = 0xe13bc5d8007f65caULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_control_msgs/ControlLeds";
  }

  static const char* value(const ::roboy_control_msgs::ControlLeds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 mode\n"
"int32 duration #seconds\n"
;
  }

  static const char* value(const ::roboy_control_msgs::ControlLeds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlLeds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_control_msgs::ControlLeds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_control_msgs::ControlLeds_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mode);
    s << indent << "duration: ";
    Printer<int32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_CONTROL_MSGS_MESSAGE_CONTROLLEDS_H
