// Generated by gencpp from file roboy_control_msgs/Emotion.msg
// DO NOT EDIT!


#ifndef ROBOY_CONTROL_MSGS_MESSAGE_EMOTION_H
#define ROBOY_CONTROL_MSGS_MESSAGE_EMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboy_control_msgs
{
template <class ContainerAllocator>
struct Emotion_
{
  typedef Emotion_<ContainerAllocator> Type;

  Emotion_()
    : header()
    , emotion()  {
    }
  Emotion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , emotion(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _emotion_type;
  _emotion_type emotion;





  typedef boost::shared_ptr< ::roboy_control_msgs::Emotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_control_msgs::Emotion_<ContainerAllocator> const> ConstPtr;

}; // struct Emotion_

typedef ::roboy_control_msgs::Emotion_<std::allocator<void> > Emotion;

typedef boost::shared_ptr< ::roboy_control_msgs::Emotion > EmotionPtr;
typedef boost::shared_ptr< ::roboy_control_msgs::Emotion const> EmotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_control_msgs::Emotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_control_msgs::Emotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'roboy_control_msgs': ['/home/sausy/Projects/Hand_openBionic/catkin/src/roboy_communication/roboy_control_msgs/msg', '/home/sausy/Projects/Hand_openBionic/catkin/devel/share/roboy_control_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::Emotion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::Emotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::Emotion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e7cfd6974e5f498c01a06ab2c37c19e";
  }

  static const char* value(const ::roboy_control_msgs::Emotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e7cfd6974e5f498ULL;
  static const uint64_t static_value2 = 0xc01a06ab2c37c19eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_control_msgs/Emotion";
  }

  static const char* value(const ::roboy_control_msgs::Emotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string emotion\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::roboy_control_msgs::Emotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.emotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Emotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_control_msgs::Emotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_control_msgs::Emotion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "emotion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.emotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_CONTROL_MSGS_MESSAGE_EMOTION_H
