// Generated by gencpp from file roboy_control_msgs/SetControllerParametersRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_CONTROL_MSGS_MESSAGE_SETCONTROLLERPARAMETERSREQUEST_H
#define ROBOY_CONTROL_MSGS_MESSAGE_SETCONTROLLERPARAMETERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_control_msgs
{
template <class ContainerAllocator>
struct SetControllerParametersRequest_
{
  typedef SetControllerParametersRequest_<ContainerAllocator> Type;

  SetControllerParametersRequest_()
    : kp(0.0)
    , kd(0.0)  {
    }
  SetControllerParametersRequest_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef double _kp_type;
  _kp_type kp;

   typedef double _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetControllerParametersRequest_

typedef ::roboy_control_msgs::SetControllerParametersRequest_<std::allocator<void> > SetControllerParametersRequest;

typedef boost::shared_ptr< ::roboy_control_msgs::SetControllerParametersRequest > SetControllerParametersRequestPtr;
typedef boost::shared_ptr< ::roboy_control_msgs::SetControllerParametersRequest const> SetControllerParametersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'roboy_control_msgs': ['/home/sausy/Projects/roboy_hand/catkin/src/roboy_communication/roboy_control_msgs/msg', '/home/sausy/Projects/roboy_hand/catkin/devel/share/roboy_control_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a1d40702f2b7265f668191485ba784e";
  }

  static const char* value(const ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a1d40702f2b7265ULL;
  static const uint64_t static_value2 = 0xf668191485ba784eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_control_msgs/SetControllerParametersRequest";
  }

  static const char* value(const ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 kp\n"
"float64 kd\n"
;
  }

  static const char* value(const ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetControllerParametersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_control_msgs::SetControllerParametersRequest_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_CONTROL_MSGS_MESSAGE_SETCONTROLLERPARAMETERSREQUEST_H
