// Generated by gencpp from file roboy_control_msgs/LookAtFeedback.msg
// DO NOT EDIT!


#ifndef ROBOY_CONTROL_MSGS_MESSAGE_LOOKATFEEDBACK_H
#define ROBOY_CONTROL_MSGS_MESSAGE_LOOKATFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_control_msgs
{
template <class ContainerAllocator>
struct LookAtFeedback_
{
  typedef LookAtFeedback_<ContainerAllocator> Type;

  LookAtFeedback_()
    : error(0.0)  {
    }
  LookAtFeedback_(const ContainerAllocator& _alloc)
    : error(0.0)  {
  (void)_alloc;
    }



   typedef float _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LookAtFeedback_

typedef ::roboy_control_msgs::LookAtFeedback_<std::allocator<void> > LookAtFeedback;

typedef boost::shared_ptr< ::roboy_control_msgs::LookAtFeedback > LookAtFeedbackPtr;
typedef boost::shared_ptr< ::roboy_control_msgs::LookAtFeedback const> LookAtFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'roboy_control_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_control_msgs/msg', '/home/sausy/Projects/Hand_openBionic/software/catkin/devel/share/roboy_control_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "417c68e466c6131d4fed652219a9ccb7";
  }

  static const char* value(const ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x417c68e466c6131dULL;
  static const uint64_t static_value2 = 0x4fed652219a9ccb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_control_msgs/LookAtFeedback";
  }

  static const char* value(const ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 error\n"
;
  }

  static const char* value(const ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LookAtFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_control_msgs::LookAtFeedback_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<float>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_CONTROL_MSGS_MESSAGE_LOOKATFEEDBACK_H
