// Generated by gencpp from file roboy_cognition_msgs/PaymentResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_PAYMENTRESPONSE_H
#define ROBOY_COGNITION_MSGS_MESSAGE_PAYMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct PaymentResponse_
{
  typedef PaymentResponse_<ContainerAllocator> Type;

  PaymentResponse_()
    : amount_paid(0)
    , customer_name()
    , error_message()  {
    }
  PaymentResponse_(const ContainerAllocator& _alloc)
    : amount_paid(0)
    , customer_name(_alloc)
    , error_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _amount_paid_type;
  _amount_paid_type amount_paid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _customer_name_type;
  _customer_name_type customer_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PaymentResponse_

typedef ::roboy_cognition_msgs::PaymentResponse_<std::allocator<void> > PaymentResponse;

typedef boost::shared_ptr< ::roboy_cognition_msgs::PaymentResponse > PaymentResponsePtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::PaymentResponse const> PaymentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_cognition_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_cognition_msgs/msg', '/home/sausy/Projects/Hand_openBionic/software/catkin/devel/share/roboy_cognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40835f67f66b050ceede2ba7ff1f0e1e";
  }

  static const char* value(const ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40835f67f66b050cULL;
  static const uint64_t static_value2 = 0xeede2ba7ff1f0e1eULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/PaymentResponse";
  }

  static const char* value(const ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 amount_paid\n"
"string customer_name\n"
"string error_message\n"
"\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.amount_paid);
      stream.next(m.customer_name);
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PaymentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::PaymentResponse_<ContainerAllocator>& v)
  {
    s << indent << "amount_paid: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.amount_paid);
    s << indent << "customer_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.customer_name);
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_PAYMENTRESPONSE_H
