// Generated by gencpp from file roboy_cognition_msgs/RecognizeObjectRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZEOBJECTREQUEST_H
#define ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZEOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct RecognizeObjectRequest_
{
  typedef RecognizeObjectRequest_<ContainerAllocator> Type;

  RecognizeObjectRequest_()
    : object_id(0)  {
    }
  RecognizeObjectRequest_(const ContainerAllocator& _alloc)
    : object_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _object_id_type;
  _object_id_type object_id;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeObjectRequest_

typedef ::roboy_cognition_msgs::RecognizeObjectRequest_<std::allocator<void> > RecognizeObjectRequest;

typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeObjectRequest > RecognizeObjectRequestPtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeObjectRequest const> RecognizeObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_cognition_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_cognition_msgs/msg', '/home/sausy/Projects/Hand_openBionic/software/catkin/devel/share/roboy_cognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bc61e324c1dd4520ddb0edb73571599";
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bc61e324c1dd452ULL;
  static const uint64_t static_value2 = 0x0ddb0edb73571599ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/RecognizeObjectRequest";
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 object_id\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::RecognizeObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.object_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZEOBJECTREQUEST_H
