// Generated by gencpp from file roboy_cognition_msgs/WhichTonesResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_WHICHTONESRESPONSE_H
#define ROBOY_COGNITION_MSGS_MESSAGE_WHICHTONESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct WhichTonesResponse_
{
  typedef WhichTonesResponse_<ContainerAllocator> Type;

  WhichTonesResponse_()
    : tones()
    , timestamps()  {
    }
  WhichTonesResponse_(const ContainerAllocator& _alloc)
    : tones(_alloc)
    , timestamps(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _tones_type;
  _tones_type tones;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _timestamps_type;
  _timestamps_type timestamps;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WhichTonesResponse_

typedef ::roboy_cognition_msgs::WhichTonesResponse_<std::allocator<void> > WhichTonesResponse;

typedef boost::shared_ptr< ::roboy_cognition_msgs::WhichTonesResponse > WhichTonesResponsePtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::WhichTonesResponse const> WhichTonesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'roboy_cognition_msgs': ['/home/sausy/Projects/Hand_openBionic/software/catkin/src/roboy_communication/roboy_cognition_msgs/msg', '/home/sausy/Projects/Hand_openBionic/software/catkin/devel/share/roboy_cognition_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a670781173fee749e2fee4de6a0bbd1";
  }

  static const char* value(const ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a670781173fee74ULL;
  static const uint64_t static_value2 = 0x9e2fee4de6a0bbd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/WhichTonesResponse";
  }

  static const char* value(const ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] tones\n"
"float32[] timestamps\n"
"\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tones);
      stream.next(m.timestamps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WhichTonesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::WhichTonesResponse_<ContainerAllocator>& v)
  {
    s << indent << "tones[]" << std::endl;
    for (size_t i = 0; i < v.tones.size(); ++i)
    {
      s << indent << "  tones[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.tones[i]);
    }
    s << indent << "timestamps[]" << std::endl;
    for (size_t i = 0; i < v.timestamps.size(); ++i)
    {
      s << indent << "  timestamps[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.timestamps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_WHICHTONESRESPONSE_H
